### ISSUE TITLE
How to check if task is running?

### ISSUE THREAD

**Issue by ChimpGamer** [A248/MorePaperLib#3]
I can't seem to find a method to check if a task is running. Is there a method present in this library to check if a task is running?
Edit: I also can't seem to find a method to check if a task is queued.

**Comment by A248** [comment]
These methods aren't available because Folia does not provide equivalents for them. The methods `isCurrentlyRunning` and `isQueued` exist on the BukkitScheduler though not on Folia's purpose-specific scheduling APIs.

**Comment by ChimpGamer** [comment]
Folia has ScheduledTask ExecutionState right? That can be used to check this. See: https://jd.papermc.io/folia/1.20/io/papermc/paper/threadedregions/scheduler/ScheduledTask.ExecutionState.html

**Comment by A248** [comment]
Thanks, you are correct. The API will mirror Folia's because it is somewhat cleaner (yielding a single enum value) and that is typically what we do in MorePaperLib. I will release this shortly.

**Comment by A248** [comment]
Released version 0.4.4.
